# Generated by Django 4.2.13 on 2026-04-04 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('incidents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('in_progress', 'In Progress'), ('findings_recorded', 'Findings Recorded'), ('recommendations_issued', 'Recommendations Issued'), ('closed', 'Closed')], db_index=True, default='initiated', max_length=30)),
                ('rca_method', models.CharField(choices=[('five_whys', '5 Whys'), ('fishbone', 'Fishbone (Ishikawa)'), ('fault_tree', 'Fault Tree Analysis'), ('bow_tie', 'Bow Tie Analysis'), ('icam', 'ICAM'), ('other', 'Other')], default='five_whys', max_length=20)),
                ('scope', models.TextField(blank=True, help_text='What this investigation covers and its boundaries.')),
                ('timeline_of_events', models.TextField(blank=True, help_text='Chronological account of events.')),
                ('immediate_causes', models.TextField(blank=True, help_text='Direct causes that led to the incident.')),
                ('contributing_factors', models.TextField(blank=True, help_text='Conditions that allowed the causes to exist.')),
                ('findings', models.TextField(blank=True, help_text='What the investigation determined.')),
                ('lessons_learned', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True, help_text='Actions recommended to prevent recurrence.')),
                ('target_completion_date', models.DateField(blank=True, null=True)),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_investigations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_investigations', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_investigations', to=settings.AUTH_USER_MODEL)),
                ('incident', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigation', to='incidents.incident')),
                ('lead_investigator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_investigations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='core.organization')),
            ],
            options={
                'db_table': 'investigations_investigation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RootCause',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('human_factors', 'Human Factors'), ('equipment_failure', 'Equipment / Plant Failure'), ('environmental', 'Environmental Conditions'), ('management_system', 'Management System Deficiency'), ('procedure', 'Procedure / Process Deficiency'), ('training', 'Training / Competency Deficiency'), ('communication', 'Communication Failure'), ('design', 'Design Deficiency'), ('external', 'External / Uncontrollable'), ('other', 'Other')], db_index=True, max_length=30)),
                ('description', models.TextField()),
                ('why_analysis', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display ordering within an investigation.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='root_causes', to='investigations.investigation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='root_causes', to='core.organization')),
            ],
            options={
                'db_table': 'investigations_root_cause',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestigationTeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to='investigations.investigation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'investigations_team_member',
                'ordering': ['added_at'],
                'unique_together': {('investigation', 'user')},
            },
        ),
        migrations.AddField(
            model_name='investigation',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='investigation_team_memberships', through='investigations.InvestigationTeamMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='InvestigationStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='investigation_status_changes', to=settings.AUTH_USER_MODEL)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='investigations.investigation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigation_status_history', to='core.organization')),
            ],
            options={
                'db_table': 'investigations_status_history',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['investigation', 'created_at'], name='investigati_investi_6e8677_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='investigation',
            index=models.Index(fields=['organization', 'status'], name='investigati_organiz_f81ca1_idx'),
        ),
        migrations.AddIndex(
            model_name='investigation',
            index=models.Index(fields=['organization', 'created_at'], name='investigati_organiz_df5a51_idx'),
        ),
        migrations.AddIndex(
            model_name='investigation',
            index=models.Index(fields=['lead_investigator', 'organization'], name='investigati_lead_in_b50e9c_idx'),
        ),
    ]
