# Generated by Django 4.2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterestedParty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('party_type', models.CharField(
                    choices=[
                        ('worker', 'Worker'),
                        ('contractor', 'Contractor'),
                        ('regulator', 'Regulator'),
                        ('supplier', 'Supplier'),
                        ('customer', 'Customer'),
                        ('community', 'Community'),
                        ('investor', 'Investor'),
                        ('other', 'Other'),
                    ],
                    default='other',
                    max_length=20,
                )),
                ('needs_and_expectations', models.TextField()),
                ('is_compliance_obligation', models.BooleanField(default=False)),
                ('review_frequency', models.CharField(
                    choices=[
                        ('annually', 'Annually'),
                        ('semi_annually', 'Semi-Annually'),
                        ('quarterly', 'Quarterly'),
                    ],
                    default='annually',
                    max_length=20,
                )),
                ('last_reviewed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(
                    choices=[('active', 'Active'), ('inactive', 'Inactive')],
                    default='active',
                    max_length=20,
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='interested_parties',
                    to='core.organization',
                )),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContextIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('type', models.CharField(
                    choices=[('internal', 'Internal'), ('external', 'External')],
                    max_length=20,
                )),
                ('analysis_tag', models.CharField(
                    choices=[
                        ('swot_strength', 'SWOT \u2014 Strength'),
                        ('swot_weakness', 'SWOT \u2014 Weakness'),
                        ('swot_opportunity', 'SWOT \u2014 Opportunity'),
                        ('swot_threat', 'SWOT \u2014 Threat'),
                        ('pestle_political', 'PESTLE \u2014 Political'),
                        ('pestle_economic', 'PESTLE \u2014 Economic'),
                        ('pestle_social', 'PESTLE \u2014 Social'),
                        ('pestle_technological', 'PESTLE \u2014 Technological'),
                        ('pestle_legal', 'PESTLE \u2014 Legal'),
                        ('pestle_environmental', 'PESTLE \u2014 Environmental'),
                        ('other', 'Other'),
                    ],
                    default='other',
                    max_length=30,
                )),
                ('classification', models.CharField(
                    choices=[('risk', 'Risk'), ('opportunity', 'Opportunity')],
                    max_length=20,
                )),
                ('status', models.CharField(
                    choices=[
                        ('open', 'Open'),
                        ('monitored', 'Monitored'),
                        ('addressed', 'Addressed'),
                        ('closed', 'Closed'),
                    ],
                    default='open',
                    max_length=20,
                )),
                ('identified_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='context_issues',
                    to='core.organization',
                )),
                ('interested_party', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='context_issues',
                    to='context.interestedparty',
                )),
                ('identified_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='identified_issues',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiskOrOpportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(
                    choices=[('risk', 'Risk'), ('opportunity', 'Opportunity')],
                    max_length=20,
                )),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity_level', models.CharField(
                    choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')],
                    max_length=20,
                )),
                ('controls', models.TextField(blank=True)),
                ('potential_benefit', models.TextField(blank=True)),
                ('status', models.CharField(
                    choices=[
                        ('open', 'Open'),
                        ('being_addressed', 'Being Addressed'),
                        ('closed', 'Closed'),
                    ],
                    default='open',
                    max_length=20,
                )),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='risks_and_opportunities',
                    to='core.organization',
                )),
                ('source_issue', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='risks_and_opportunities',
                    to='context.contextissue',
                )),
                ('owner', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='owned_risks_opportunities',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'ordering': ['-created_at'],
                'verbose_name_plural': 'Risks and Opportunities',
            },
        ),
    ]
