# Generated by Django 4.2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementSystemScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_statement', models.TextField(
                    help_text='Formal statement of what the OH&S management system covers.',
                )),
                ('boundaries_and_applicability', models.TextField(
                    blank=True,
                    help_text='Physical locations, organizational units, activities included/excluded.',
                )),
                ('activities_products_services', models.TextField(
                    blank=True,
                    help_text='Main activities, products, and services within scope.',
                )),
                ('exclusions', models.TextField(
                    blank=True,
                    help_text='Anything explicitly excluded from the scope, with justification.',
                )),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='ohsms_scope',
                    to='core.organization',
                )),
                ('updated_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='scope_updates',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'verbose_name': 'Management System Scope',
            },
        ),
    ]
