# Generated by Django 4.2.13 on 2026-05-05 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0002_managementsystemscope'),
    ]

    operations = [
        migrations.AddField(
            model_name='interestedparty',
            name='category',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='internal', max_length=20),
        ),
    ]
