# Generated by Django 4.2.13 on 2026-04-05 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('investigations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('action_type', models.CharField(choices=[('corrective', 'Corrective'), ('preventive', 'Preventive'), ('improvement', 'Improvement Opportunity')], default='corrective', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('implemented', 'Implemented — Awaiting Review'), ('closed', 'Closed'), ('reopened', 'Reopened')], db_index=True, default='open', max_length=20)),
                ('source_type', models.CharField(choices=[('investigation', 'Investigation'), ('incident', 'Incident'), ('audit', 'Audit'), ('risk_assessment', 'Risk Assessment'), ('management_review', 'Management Review'), ('other', 'Other')], default='other', max_length=20)),
                ('planned_action', models.TextField(blank=True, default='')),
                ('implementation_notes', models.TextField(blank=True, default='')),
                ('implementation_evidence', models.TextField(blank=True, default='')),
                ('target_date', models.DateField(blank=True, null=True)),
                ('implementation_date', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_corrective_actions', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_corrective_actions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_corrective_actions', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_corrective_actions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrective_actions', to='core.organization')),
                ('source_incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrective_actions', to='incidents.incident')),
                ('source_investigation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrective_actions', to='investigations.investigation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EffectivenessReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review_date', models.DateField()),
                ('rating', models.CharField(choices=[('fully_effective', 'Fully Effective'), ('partially_effective', 'Partially Effective'), ('not_effective', 'Not Effective')], max_length=25)),
                ('evidence_description', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('next_review_date', models.DateField(blank=True, help_text='Required when rating is Partially Effective or Not Effective.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('corrective_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effectiveness_reviews', to='corrective_actions.correctiveaction')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='effectiveness_reviews', to='core.organization')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='effectiveness_reviews_conducted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-review_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CorrectiveActionStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, default='', max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('comment', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ca_status_changes', to=settings.AUTH_USER_MODEL)),
                ('corrective_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='corrective_actions.correctiveaction')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ca_status_history', to='core.organization')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='correctiveaction',
            index=models.Index(fields=['organization', 'status'], name='corrective__organiz_9608ba_idx'),
        ),
        migrations.AddIndex(
            model_name='correctiveaction',
            index=models.Index(fields=['organization', 'is_deleted'], name='corrective__organiz_81caee_idx'),
        ),
        migrations.AddIndex(
            model_name='correctiveaction',
            index=models.Index(fields=['assigned_to', 'status'], name='corrective__assigne_c32fcc_idx'),
        ),
    ]
