# Generated by Django 4.2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('scope', models.CharField(
                    choices=[('organizational', 'Organizational'), ('individual', 'Individual')],
                    default='organizational',
                    max_length=20,
                )),
                ('category', models.CharField(
                    choices=[('lagging', 'Lagging'), ('leading', 'Leading')],
                    default='lagging',
                    max_length=20,
                )),
                ('unit', models.CharField(help_text='e.g. count, %, rate, days', max_length=50)),
                ('direction', models.CharField(
                    choices=[('increase', 'Increase'), ('decrease', 'Decrease'), ('maintain', 'Maintain')],
                    default='decrease',
                    max_length=20,
                )),
                ('measurement_frequency', models.CharField(
                    choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('bi_annually', 'Bi-Annually')],
                    default='monthly',
                    max_length=20,
                )),
                ('linked_metric', models.CharField(
                    choices=[
                        ('manual', 'Manual Entry'),
                        ('near_miss_count', 'Near Miss Count'),
                        ('total_incident_count', 'Total Incident Count'),
                        ('injury_count', 'Injury Count'),
                        ('critical_incident_count', 'Critical Incident Count'),
                        ('open_incident_count', 'Open Incident Count'),
                        ('overdue_ca_count', 'Overdue Corrective Actions'),
                        ('ca_closure_rate', 'CA On-Time Closure Rate (%)'),
                        ('open_investigation_count', 'Open Investigation Count'),
                    ],
                    default='manual',
                    max_length=50,
                )),
                ('baseline_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('target_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('weight', models.PositiveIntegerField(default=1, help_text='Relative weight for scoring')),
                ('status', models.CharField(
                    choices=[
                        ('on_track', 'On Track'),
                        ('at_risk', 'At Risk'),
                        ('behind', 'Behind'),
                        ('achieved', 'Achieved'),
                        ('closed', 'Closed'),
                    ],
                    default='on_track',
                    max_length=20,
                )),
                ('start_date', models.DateField()),
                ('target_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='created_objectives',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('organization', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='objectives',
                    to='core.organization',
                )),
                ('owner', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='owned_objectives',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KPIMeasurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('measured_at', models.DateField(help_text='The period this measurement covers')),
                ('notes', models.TextField(blank=True)),
                ('is_auto_computed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('objective', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='measurements',
                    to='objectives.objective',
                )),
                ('recorded_by', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='recorded_measurements',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'ordering': ['measured_at'],
            },
        ),
    ]
