# Generated by Django 4.2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('objectives', '0002_objective_risk_or_opportunity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Planning fields
        migrations.AddField(
            model_name='objective',
            name='present_status',
            field=models.TextField(
                blank=True,
                help_text='Description of the current state that this objective aims to improve.',
            ),
        ),
        migrations.AddField(
            model_name='objective',
            name='kpi_description',
            field=models.CharField(
                blank=True,
                max_length=255,
                help_text="Explicit KPI statement, e.g. 'LTI frequency rate per 200,000 hrs worked'.",
            ),
        ),
        migrations.AddField(
            model_name='objective',
            name='planned_actions',
            field=models.TextField(
                blank=True,
                help_text='Specific actions planned to achieve this objective.',
            ),
        ),
        migrations.AddField(
            model_name='objective',
            name='responsible_persons',
            field=models.TextField(
                blank=True,
                help_text='Individuals, teams, or committees responsible beyond the primary owner.',
            ),
        ),
        migrations.AddField(
            model_name='objective',
            name='expected_result',
            field=models.TextField(
                blank=True,
                help_text='Expected outcome from the planned actions and mitigations.',
            ),
        ),
        # Review fields
        migrations.AddField(
            model_name='objective',
            name='effectiveness_decision',
            field=models.CharField(
                choices=[
                    ('pending', 'Pending Review'),
                    ('effective', 'Effective'),
                    ('partially_effective', 'Partially Effective'),
                    ('not_effective', 'Not Effective'),
                ],
                default='pending',
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name='objective',
            name='effectiveness_notes',
            field=models.TextField(
                blank=True,
                help_text='Narrative supporting the effectiveness decision.',
            ),
        ),
        migrations.AddField(
            model_name='objective',
            name='evidence_of_review',
            field=models.TextField(
                blank=True,
                help_text='References to meeting minutes, reports, or documents that evidence the review.',
            ),
        ),
        migrations.AddField(
            model_name='objective',
            name='final_result',
            field=models.TextField(
                blank=True,
                help_text='Documented final outcome once the objective period is complete.',
            ),
        ),
        migrations.AddField(
            model_name='objective',
            name='review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='objective',
            name='reviewed_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='reviewed_objectives',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
