# Generated by Django 4.2.13 on 2026-04-04 15:14

import apps.incidents.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('incident_type', models.CharField(choices=[('near_miss', 'Near Miss'), ('injury', 'Injury'), ('first_aid', 'First Aid Case'), ('medical_treatment', 'Medical Treatment Case'), ('lost_time_injury', 'Lost Time Injury'), ('fatality', 'Fatality'), ('property_damage', 'Property Damage'), ('environmental_spill', 'Environmental Spill'), ('unsafe_act', 'Unsafe Act'), ('unsafe_condition', 'Unsafe Condition'), ('fire', 'Fire'), ('vehicle_incident', 'Vehicle Incident'), ('other', 'Other')], db_index=True, max_length=30)),
                ('date_of_incident', models.DateField()),
                ('time_of_incident', models.TimeField(blank=True, null=True)),
                ('location_detail', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('persons_involved', models.JSONField(blank=True, default=list)),
                ('witnesses', models.JSONField(blank=True, default=list)),
                ('immediate_action_taken', models.TextField(blank=True)),
                ('injury_occurred', models.BooleanField(default=False)),
                ('environmental_impact', models.BooleanField(default=False)),
                ('property_damage', models.BooleanField(default=False)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='low', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reported', 'Reported'), ('under_review', 'Under Review'), ('investigation_ongoing', 'Investigation Ongoing'), ('actions_implemented', 'Actions Implemented'), ('closed', 'Closed'), ('reopened', 'Reopened')], db_index=True, default='draft', max_length=30)),
                ('report_date', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closure_notes', models.TextField(blank=True)),
                ('investigation_id', models.UUIDField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_incidents', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_incidents', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='core.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='core.organization')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_incidents', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='core.site')),
            ],
            options={
                'db_table': 'incidents_incident',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.incidents.models.incident_attachment_upload_path)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveIntegerField()),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('is_photo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='incidents.incident')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_attachments', to='core.organization')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_incident_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'incidents_attachment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incident_status_changes', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='incidents.incident')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_status_history', to='core.organization')),
            ],
            options={
                'db_table': 'incidents_status_history',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['incident', 'created_at'], name='incidents_s_inciden_d6e171_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['organization', 'status'], name='incidents_i_organiz_09b358_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['organization', 'created_at'], name='incidents_i_organiz_6cc078_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['organization', 'incident_type'], name='incidents_i_organiz_2d1a77_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['organization', 'severity'], name='incidents_i_organiz_a34e39_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['reported_by', 'organization'], name='incidents_i_reporte_2ae9a6_idx'),
        ),
    ]
