# Generated by Django 4.2.13 on 2026-04-08 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousIncidentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('incident_type', models.CharField(choices=[('near_miss', 'Near Miss'), ('injury', 'Injury'), ('first_aid', 'First Aid Case'), ('medical_treatment', 'Medical Treatment Case'), ('lost_time_injury', 'Lost Time Injury'), ('fatality', 'Fatality'), ('property_damage', 'Property Damage'), ('environmental_spill', 'Environmental Spill'), ('unsafe_act', 'Unsafe Act'), ('unsafe_condition', 'Unsafe Condition'), ('fire', 'Fire'), ('vehicle_incident', 'Vehicle Incident'), ('other', 'Other')], default='near_miss', max_length=30)),
                ('date_of_incident', models.DateField()),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('immediate_action_taken', models.TextField(blank=True, default='')),
                ('reporter_name', models.CharField(blank=True, default='', max_length=255)),
                ('reporter_contact', models.CharField(blank=True, default='', max_length=255)),
                ('is_reviewed', models.BooleanField(db_index=True, default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('converted_incident', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anonymous_source', to='incidents.incident')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anonymous_reports', to='core.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_anonymous_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
