# Generated by Django 4.2.13 on 2026-04-08 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('corrective_actions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('audit_type', models.CharField(choices=[('internal', 'Internal Audit'), ('external', 'External Audit'), ('surveillance', 'Surveillance Audit'), ('certification', 'Certification Audit'), ('inspection', 'Inspection'), ('management_review', 'Management Review')], default='internal', max_length=30)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='planned', max_length=20)),
                ('scope', models.TextField(blank=True, default='')),
                ('objectives', models.TextField(blank=True, default='')),
                ('criteria', models.TextField(blank=True, default='', help_text='Standards / clauses being audited against')),
                ('planned_date', models.DateField()),
                ('actual_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('auditee', models.CharField(blank=True, default='', help_text='Person / team / area being audited', max_length=255)),
                ('summary', models.TextField(blank=True, default='')),
                ('overall_conclusion', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_audits', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='core.department')),
                ('lead_auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_audits', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='core.organization')),
            ],
            options={
                'ordering': ['-planned_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditFinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('severity', models.CharField(choices=[('observation', 'Observation'), ('minor_nc', 'Minor Non-Conformance'), ('major_nc', 'Major Non-Conformance'), ('opportunity', 'Opportunity for Improvement')], default='observation', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('raised', 'CA Raised'), ('closed', 'Closed')], default='open', max_length=10)),
                ('clause_reference', models.CharField(blank=True, default='', help_text='e.g. ISO 45001 Clause 9.2.2', max_length=100)),
                ('evidence', models.TextField(blank=True, default='')),
                ('recommended_action', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='audits.audit')),
                ('corrective_action', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_finding', to='corrective_actions.correctiveaction')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
