# Generated by Django 4.2.13 on 2026-04-08 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('requirement_type', models.CharField(choices=[('legislation', 'Legislation / Act'), ('regulation', 'Regulation / Statutory Instrument'), ('standard', 'Standard (e.g. ISO, AS/NZS)'), ('code_of_practice', 'Code of Practice'), ('permit', 'Permit / Licence / Approval'), ('agreement', 'Contractual / Agreement'), ('other', 'Other')], default='legislation', max_length=25)),
                ('jurisdiction', models.CharField(choices=[('international', 'International'), ('national', 'National / Federal'), ('state', 'State / Provincial'), ('local', 'Local / Municipal'), ('industry', 'Industry / Sector')], default='national', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('applicable_clauses', models.CharField(blank=True, default='', help_text='Specific clauses, sections, or articles that apply', max_length=500)),
                ('source_url', models.URLField(blank=True, default='', help_text='Link to official document / register')),
                ('compliance_status', models.CharField(choices=[('compliant', 'Compliant'), ('partially_compliant', 'Partially Compliant'), ('non_compliant', 'Non-Compliant'), ('not_assessed', 'Not Yet Assessed'), ('not_applicable', 'Not Applicable')], db_index=True, default='not_assessed', max_length=25)),
                ('compliance_notes', models.TextField(blank=True, default='')),
                ('compliance_evidence', models.TextField(blank=True, default='')),
                ('effective_date', models.DateField(blank=True, help_text='When the requirement came into effect', null=True)),
                ('review_date', models.DateField(blank=True, help_text='Next scheduled compliance review', null=True)),
                ('last_reviewed_date', models.DateField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_legal_requirements', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_requirements', to='core.department')),
                ('last_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_requirements_last_reviewed', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_requirements', to='core.organization')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legal_requirements_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['requirement_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LegalComplianceReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('review_date', models.DateField()),
                ('compliance_status', models.CharField(choices=[('compliant', 'Compliant'), ('partially_compliant', 'Partially Compliant'), ('non_compliant', 'Non-Compliant'), ('not_assessed', 'Not Yet Assessed'), ('not_applicable', 'Not Applicable')], max_length=25)),
                ('findings', models.TextField(blank=True, default='')),
                ('evidence', models.TextField(blank=True, default='')),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='legal.legalrequirement')),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legal_reviews_conducted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-review_date', '-created_at'],
            },
        ),
    ]
