# Generated by Django 4.2.13 on 2026-04-08 11:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HazardAssessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_number', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('work_area', models.CharField(blank=True, max_length=255)),
                ('assessment_date', models.DateField()),
                ('next_review_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('under_review', 'Under Review'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conducted_assessments', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_assessments', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hazard_assessments', to='core.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hazard_assessments', to='core.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'risk_assessments_assessment',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Hazard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hazard_description', models.TextField()),
                ('hazard_category', models.CharField(choices=[('physical', 'Physical'), ('chemical', 'Chemical'), ('biological', 'Biological'), ('ergonomic', 'Ergonomic'), ('psychosocial', 'Psychosocial'), ('electrical', 'Electrical'), ('fire', 'Fire & Explosion'), ('environmental', 'Environmental'), ('mechanical', 'Mechanical'), ('other', 'Other')], default='physical', max_length=20)),
                ('who_is_at_risk', models.CharField(blank=True, max_length=255)),
                ('existing_controls', models.TextField(blank=True)),
                ('likelihood_before', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('consequence_before', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('risk_rating_before', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('risk_level_before', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', editable=False, max_length=10)),
                ('additional_controls', models.TextField(blank=True)),
                ('target_date', models.DateField(blank=True, null=True)),
                ('likelihood_after', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('consequence_after', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('risk_rating_after', models.PositiveSmallIntegerField(blank=True, editable=False, null=True)),
                ('risk_level_after', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], editable=False, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hazards', to='risk_assessments.hazardassessment')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_hazards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'risk_assessments_hazard',
                'ordering': ['created_at'],
            },
        ),
    ]
